import { Router } from "express";
import { PostController } from "../controllers/post-controller.js";
import { postService } from "../services/instances.js";
import { requireAuth, optionalAuth } from "../middlewares/require-auth.js";
const router = Router();
const controller = new PostController(postService);
router.get("/upload-url", requireAuth, controller.getUploadUrl);
router.post("/", requireAuth, controller.createPost);
router.get("/news", controller.getNewsFeed);
router.get("/user/:authorId", controller.getPostsByUser);
router.get("/:authorId/:postId", optionalAuth, controller.getPost);
router.delete("/:authorId/:postId", requireAuth, controller.deletePost);
export default router;
